<template>
  <div><PageTitle eyebrow="学习概览" title="把今天的学习变成一个闭环" :description="`围绕“${learningState.goal}”，系统会把目标、掌握度和下一步行动放在同一张桌面上。`" /><div class="grid grid--three overview-metrics"><section v-for="metric in metrics" :key="metric.label" class="surface surface-pad metric"><span class="metric-label">{{ metric.label }}</span><strong class="metric-value">{{ metric.value }}</strong><span class="muted">{{ metric.note }}</span></section></div><div class="overview-grid"><section class="surface surface-pad"><div class="section-title"><div><p class="eyebrow">当前学习主线</p><h2>从理解到能做出来</h2></div><RouterLink class="text-link" to="/learning/navigation">查看全部 →</RouterLink></div><div class="stage-list"><StageCard v-for="stage in stages" :key="stage.index" v-bind="stage" /></div></section><RecommendationPanel message="先完成“文档切分与召回评估”的基础讲解，再用一个小型知识库验证结果。完成后系统会解锁企业案例。" to="/learning/fundamentals" action-label="开始基础讲解" /></div></div>
</template>
<script setup>
import { computed } from 'vue'; import PageTitle from '@/shared/ui/PageTitle.vue'; import StageCard from '@/widgets/learning/StageCard.vue'; import RecommendationPanel from '@/widgets/learning/RecommendationPanel.vue'; import { learningState } from '@/entities/learning/learningState'
const metrics = computed(() => [{ label: '当前方向', value: learningState.direction, note: '学习定向已确认' }, { label: '综合掌握度', value: '42%', note: '较上次提升 6%' }, { label: '本周学习时长', value: '3.5h', note: '已完成 2 个任务' }])
const stages = [{ index: '01', title: '基础讲解', description: '建立领域概念和通用方法，形成可复述的知识框架。', progress: 62, state: 'active', to: '/learning/fundamentals' }, { index: '02', title: '进阶学习', description: '把方法迁移到目标场景，完成可验证的决策练习。', progress: 18, state: 'locked', to: '/learning/advanced' }, { index: '03', title: '学习工作区', description: '在文档、检索结果和笔记之间完成一次完整实践。', progress: 0, state: 'locked', to: '/learning/workspace' }]
</script>
<style scoped>
.overview-grid { display: grid; grid-template-columns: minmax(0, 1.4fr) minmax(280px, .6fr); gap: 18px; margin-top: 18px; }.section-title { display: flex; align-items: flex-start; justify-content: space-between; gap: 15px; margin-bottom: 20px; }.section-title h2 { margin: 0; font-size: 20px; }.section-title .eyebrow { margin-bottom: 5px; }.text-link { color: var(--accent-deep); font-size: 12px; font-weight: 800; text-decoration: none; }.stage-list { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 12px; }.stage-list :deep(.surface) { box-shadow: none; } 
@media (max-width: 960px) { .overview-grid { grid-template-columns: 1fr; } .stage-list { grid-template-columns: 1fr; } }
</style>
