<template>
  <div><PageTitle eyebrow="任务分析" title="先看清要解决的问题" description="把学习目标拆成可执行任务，同时显示每项能力的掌握状态。" /><div class="analysis-grid"><section class="surface surface-pad"><div class="analysis-block"><span class="block-label">当前目标</span><h2>{{ learningState.goal }}</h2><p>完成一个知识库检索优化微型项目，能够解释方案、验证效果并记录决策。</p></div><div class="analysis-block"><span class="block-label">涉及学科</span><div class="tag-list"><span v-for="tag in subjects" :key="tag" class="tag">{{ tag }}</span></div></div><div class="analysis-block"><span class="block-label">能力掌握度</span><div class="mastery-list"><div v-for="item in mastery" :key="item.label" class="mastery-row"><div><span>{{ item.label }}</span><strong>{{ item.value }}%</strong></div><div class="progress-track"><div class="progress-value" :style="{ width: `${item.value}%` }"></div></div></div></div></div></section><RecommendationPanel title="本阶段建议" message="先补齐文档切分和召回评估的基础方法，再做一次小样本对比。这个顺序能直接降低后续案例的试错成本。" to="/learning/fundamentals" action-label="进入基础讲解" /></div></div>
</template>
<script setup>
import PageTitle from '@/shared/ui/PageTitle.vue'; import RecommendationPanel from '@/widgets/learning/RecommendationPanel.vue'; import { learningState } from '@/entities/learning/learningState'
const subjects = ['RAG 检索增强', '文档工程', '评估与调优']; const mastery = [{ label: 'RAG 基础', value: learningState.mastery.rag }, { label: 'Agent 协同', value: learningState.mastery.agent }, { label: '效果评估', value: learningState.mastery.evaluation }]
</script>
<style scoped>
.analysis-grid { display: grid; grid-template-columns: minmax(0, 1.35fr) minmax(280px, .65fr); gap: 18px; }.analysis-block + .analysis-block { margin-top: 28px; padding-top: 24px; border-top: 1px solid var(--line); }.block-label { color: var(--muted); font-size: 11px; font-weight: 800; letter-spacing: .08em; text-transform: uppercase; }.analysis-block h2 { margin: 10px 0 8px; font-size: 22px; }.analysis-block p { max-width: 650px; margin: 0; color: var(--muted); font-size: 13px; line-height: 1.75; }.tag-list { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 13px; }.tag { padding: 7px 10px; border-radius: 4px; background: var(--soft); color: var(--accent-deep); font-size: 12px; font-weight: 700; }.mastery-list { display: grid; gap: 16px; margin-top: 14px; }.mastery-row { display: grid; gap: 7px; }.mastery-row > div:first-child { display: flex; justify-content: space-between; color: var(--muted); font-size: 12px; }.mastery-row strong { color: var(--ink); }
@media (max-width: 900px) { .analysis-grid { grid-template-columns: 1fr; } }
</style>
